---
swagger: '2.0'
info:
  title: GoB Company API
  version: v1
paths:
  "/sessions":
    post:
      summary: Authenticate with email and password
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: credentials
        in: body
        schema:
          type: object
          properties:
            email:
              type: string
              format: email
            password:
              type: string
          required:
          - email
          - password
      responses:
        '200':
          description: authentication successful
          schema:
            type: object
            properties:
              token:
                type: string
                description: Token to use for Autentication
              required:
              - token
        '422':
          description: authentication failed
          schema:
            type: object
            properties:
              errors:
                type: object
                properties:
                  email:
                    type: array
                    items:
                      type: string
                  password:
                    type: array
                    items:
                      type: string
              required:
              - token
