---
swagger: '2.0'
info:
  title: GoB Company API
  version: v1
paths:
  "/jobs/active":
    get:
      summary: List active jobs
      consumes:
      - application/json
      produces:
      - application/json
      security:
      - token: []
      responses:
        '200':
          description: list of active jobs
          schema:
            type: array
            items:
              "$ref": "#/definitions/job_iteration_object"
  "/jobs/closed":
    get:
      summary: List active jobs
      consumes:
      - application/json
      produces:
      - application/json
      security:
      - token: []
      responses:
        '200':
          description: list of closed jobs
          schema:
            type: array
            items:
              "$ref": "#/definitions/job_iteration_object"
  "/jobs/{slug}/processes/{id}":
    get:
      summary: Job detail
      consumes:
      - application/json
      produces:
      - application/json
      security:
      - token: []
      parameters:
      - name: slug
        in: path
        type: string
        required: true
      - name: id
        in: path
        type: integer
        required: true
      responses:
        '200':
          description: details of a job
          schema:
            "$ref": "#/definitions/job_object"
  "/sessions":
    post:
      summary: Authenticate with email and password
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: credentials
        in: body
        schema:
          type: object
          properties:
            email:
              type: string
              format: email
            password:
              type: string
          required:
          - email
          - password
      responses:
        '200':
          description: authentication successful
          schema:
            type: object
            properties:
              token:
                type: string
                description: Token to use for Autentication
              required:
              - token
        '422':
          description: authentication failed
          schema:
            type: object
            properties:
              errors:
                type: object
                properties:
                  email:
                    type: array
                    items:
                      type: string
                  password:
                    type: array
                    items:
                      type: string
              required:
              - token
securityDefinitions:
  token:
    type: apiKey
    name: Authorization
    in: header
definitions:
  job_iteration_object:
    type: object
    properties:
      url:
        type: string
      title:
        type: string
    required:
    - url
    - title
  job_object:
    type: object
    properties:
      active:
        type: boolean
      url:
        type: string
      title:
        type: string
      min_salary:
        type: integer
      max_salary:
        type: integer
      remote:
        type: boolean
      city:
        type: string
      country:
        type: string
      category_name:
        type: string
      tags:
        type: array
        items:
          type: string
      perks:
        type: array
        items:
          type: string
      modality:
        type: string
      seniority:
        type: string
      functions:
        type: string
      functions_headline:
        type: string
      benefits:
        type: string
      benefits_headline:
        type: string
      desirable:
        type: string
      desirable_headline:
        type: string
      unpublished:
        type: boolean
      public_url:
        type: string
      company_public_url:
        type: string
      company_name:
        type: object
        properties:
          name:
            type: string
          about:
            type: string
          url:
            type: string
      phases:
        type: array
        items:
          "$ref": "#/definitions/phase_object"
  phase_object:
    type: object
    properties:
      position:
        type: integer
      title:
        type: string
      kind:
        type: string
      job_applications_count:
        type: integer
      job_applications_url:
        type: string
